### PR TITLE
Fix hero height issue on small screens

### LINKED ISSUE #63: Interior pages - Hero is overlapping nav on smaller screen sizes

### PR DESCRIPTION
**Pull request by kcbreuil**
closes #63

### CODE REVIEW

**Comment by kcbreuil** [comment]
@asasmith this fixed it BUT i want you to let me know how you feel about the look of it

File: src/components/altHero.js [hunk 1]
```diff
@@ -4,7 +4,7 @@ import styled from 'styled-components';
 import tw from 'twin.macro';
 
 const StyledSection = styled.section`
-    ${tw`min-h-screen md:min-h-0 md:h-3/4-screen flex flex-col justify-center pb-8 text-white`}
+    ${tw`min-h-screen md:min-h-0 md:h-screen lg:h-screen flex flex-col justify-center pb-8 text-white`}
```
Comment (asasmith) [inline src/components/altHero.js:7]: Let's remove `md:min-h-0 md:h-screen lg:h-screen`. That will leave the min-height to be the full height of the screen but if the content is larger the component should size up to match.

As a side note `md:h-screen lg:h-screen` is redundant. You would only use the `lg:` prefix if you wanted to apply new styles at that breakpoint.

**Review by asasmith — APPROVED** [review]
